version: "3.8"
services:
  app2:
    container_name: app2
    build:
      context: .
      target: php
      args:
        - APP_ENV=${APP_ENV}
    environment:
      - APP_ENV=${APP_ENV}
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "8082:8080"
      - '${VITE_PORT:-5175}:${VITE_PORT:-5175}'
    networks:
        - mysql-container_mysql_network
networks:
    mysql-container_mysql_network:
        external: true
